<?php

namespace AppBundle\Repository;

/**
 * TodoItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoItemRepository extends \Doctrine\ORM\EntityRepository
{
}
